"""Phase 2 (mechanism) — affixes, slot structure, and positional entropy.

The register study showed the Voynich's low h2 is not a vocabulary/register effect. The
hypothesis now: it is generated by a rigid POSITIONAL word template (a slot grammar) — some
glyphs only begin words, some only end them. If that is right, then knowing a glyph's
*position in its word* should predict it almost as well as knowing the *previous glyph*
(which is what h2 measures) — and that should be true for the Voynich but NOT for a real
language.

We test three things per series (Voynich under eva1 AND evaG; languages under chars):
  A. Affixes   : top prefixes/suffixes and how much token mass they cover.
  B. Positional entropy: h1 (unconditional) vs within-word h2 (given previous glyph) vs
     h_startpos / h_endpos (given position from the word's start / end) vs first/last-glyph
     entropy. The mechanism metric is the "positional explanatory ratio":
         (h1 - h_pos) / (h1 - h2_within)
     ~1 means position is as informative as the previous glyph (template-driven); ~0 means
     position tells you nothing (language-like).
  C. Per-position entropy profile (normalised position 0..1) for the figure.

NOTE all bigrams/positions here are WITHIN words (they do not cross word boundaries), unlike
the headline h2 in discriminators.py which concatenates the stream. Within-word is the right
frame for word-internal structure.

Writes results/slot_grammar.json + figures/slot_entropy.png, figures/affix_coverage.png.
"""
import json
from collections import Counter

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

import seriesio as S
from glyphkit import glyphs, H, cond_H

RES = S.ROOT / "results"
FIG = S.ROOT / "figures"

# (series, grouped?, label, color)
SETUPS = [
    ("voynich_eva", False, "Voynich (eva1)", "red"),
    ("voynich_eva", True, "Voynich (evaG)", "#b30000"),
    ("english", False, "English", "#1f77b4"),
    ("latin", False, "Latin", "#17becf"),
    ("german", False, "German", "#8c564b"),
    ("hebrew", False, "Hebrew (abjad)", "#2f4f4f"),
    ("monkey", False, "monkey null", "grey"),
]
NPOS_BINS = 10


def affixes(seqs, k=2):
    """top length-1 and length-2 prefixes/suffixes with cumulative token coverage."""
    n = len(seqs)
    out = {}
    for side in ("prefix", "suffix"):
        for L in (1, 2):
            c = Counter()
            for g in seqs:
                if len(g) >= L:
                    key = "".join(g[:L]) if side == "prefix" else "".join(g[-L:])
                    c[key] += 1
            top = c.most_common(10)
            cov = sum(n for _, n in top) / n
            out[f"{side}{L}"] = {"top": top[:8], "top10_coverage": round(cov, 3)}
    return out


def positional(seqs):
    uni = Counter()
    biw = []          # within-word (prev, cur)
    startp = []       # (pos_from_start, glyph)
    endp = []         # (pos_from_end, glyph)
    first = Counter()
    last = Counter()
    prof = [Counter() for _ in range(NPOS_BINS)]  # entropy profile by normalised position
    for g in seqs:
        L = len(g)
        if L == 0:
            continue
        first[g[0]] += 1
        last[g[-1]] += 1
        for i, ch in enumerate(g):
            uni[ch] += 1
            startp.append((i, ch))
            endp.append((L - 1 - i, ch))
            if i > 0:
                biw.append((g[i - 1], ch))
            b = min(int(i / L * NPOS_BINS), NPOS_BINS - 1) if L > 1 else 0
            prof[b][ch] += 1
    h1 = H(uni)
    h2w = cond_H(biw)
    hs = cond_H(startp)
    he = cond_H(endp)
    info_prev = h1 - h2w
    ratio_start = (h1 - hs) / info_prev if info_prev > 1e-9 else float("nan")
    ratio_end = (h1 - he) / info_prev if info_prev > 1e-9 else float("nan")
    return {
        "h1": round(h1, 3), "h2_within": round(h2w, 3),
        "h_startpos": round(hs, 3), "h_endpos": round(he, 3),
        "h_first_glyph": round(H(first), 3), "h_last_glyph": round(H(last), 3),
        "info_from_prev_glyph": round(info_prev, 3),
        "positional_ratio_start": round(ratio_start, 3),
        "positional_ratio_end": round(ratio_end, 3),
        "positional_ratio_best": round(max(ratio_start, ratio_end), 3),
        "_profile": [round(H(c), 3) for c in prof],
        "n_glyph_types": len(uni),
    }


def main():
    RES.mkdir(exist_ok=True); FIG.mkdir(exist_ok=True)
    out = {}
    profiles = {}
    for name, grouped, label, color in SETUPS:
        toks = S.load_tokens(name)
        seqs = [glyphs(t, grouped) for t in toks]
        pos = positional(seqs)
        profiles[label] = (pos.pop("_profile"), color)
        out[label] = {"series": name, "grouped": grouped,
                      "affixes": affixes(seqs), **pos}

    (RES / "slot_grammar.json").write_text(json.dumps(out, indent=2), encoding="utf-8")

    # ---- figure 1: positional entropy profile + first/last bars ----
    fig, (axA, axB) = plt.subplots(1, 2, figsize=(13, 5.2))
    xs = (np.arange(NPOS_BINS) + 0.5) / NPOS_BINS
    for label, (prof, color) in profiles.items():
        axA.plot(xs, prof, marker="o", ms=4, color=color,
                 lw=2.4 if "Voynich" in label else 1.6, label=label)
    axA.set_xlabel("normalised position in word (0=start, 1=end)")
    axA.set_ylabel("glyph entropy at that position (bits)")
    axA.set_title("Per-position entropy — Voynich edges are rigid")
    axA.grid(True, ls=":", alpha=0.3); axA.legend(fontsize=8)

    labels = list(out.keys())
    x = np.arange(len(labels)); w = 0.38
    axB.bar(x - w / 2, [out[l]["h_first_glyph"] for l in labels], w, label="first glyph", color="#4c72b0")
    axB.bar(x + w / 2, [out[l]["h_last_glyph"] for l in labels], w, label="last glyph", color="#dd8452")
    axB.set_xticks(x); axB.set_xticklabels([l.replace(" (", "\n(") for l in labels], fontsize=7)
    axB.set_ylabel("entropy (bits)")
    axB.set_title("First / last glyph entropy (low = rigid affixes)")
    axB.grid(True, axis="y", ls=":", alpha=0.3); axB.legend(fontsize=8)
    fig.tight_layout(); fig.savefig(FIG / "slot_entropy.png", dpi=140); plt.close(fig)

    # ---- figure 2: affix coverage (prefix2 / suffix2 top-10 coverage) ----
    fig, ax = plt.subplots(figsize=(8, 5))
    pcov = [out[l]["affixes"]["prefix2"]["top10_coverage"] for l in labels]
    scov = [out[l]["affixes"]["suffix2"]["top10_coverage"] for l in labels]
    ax.bar(x - w / 2, pcov, w, label="top-10 2-glyph prefixes", color="#55a868")
    ax.bar(x + w / 2, scov, w, label="top-10 2-glyph suffixes", color="#c44e52")
    ax.set_xticks(x); ax.set_xticklabels([l.replace(" (", "\n(") for l in labels], fontsize=7)
    ax.set_ylabel("fraction of tokens covered")
    ax.set_title("How much word mass a tiny affix kit explains")
    ax.grid(True, axis="y", ls=":", alpha=0.3); ax.legend(fontsize=8)
    fig.tight_layout(); fig.savefig(FIG / "affix_coverage.png", dpi=140); plt.close(fig)

    # ---- console verdict ----
    print(f"  {'series':18s} {'h1':>5s} {'h2w':>5s} {'hStart':>7s} {'hEnd':>6s} "
          f"{'hFirst':>7s} {'hLast':>6s} {'ratioS':>7s} {'ratioE':>7s}")
    for l in labels:
        d = out[l]
        print(f"  {l:18s} {d['h1']:5.2f} {d['h2_within']:5.2f} {d['h_startpos']:7.2f} "
              f"{d['h_endpos']:6.2f} {d['h_first_glyph']:7.2f} {d['h_last_glyph']:6.2f} "
              f"{d['positional_ratio_start']:7.2f} {d['positional_ratio_end']:7.2f}")
    print("\n  top 2-glyph suffixes:")
    for l in labels:
        top = out[l]["affixes"]["suffix2"]["top"]
        cov = out[l]["affixes"]["suffix2"]["top10_coverage"]
        print(f"    {l:18s} cov={cov:.2f}  " + " ".join(f"{k}:{n}" for k, n in top[:6]))
    print("\n  top 2-glyph prefixes:")
    for l in labels:
        top = out[l]["affixes"]["prefix2"]["top"]
        cov = out[l]["affixes"]["prefix2"]["top10_coverage"]
        print(f"    {l:18s} cov={cov:.2f}  " + " ".join(f"{k}:{n}" for k, n in top[:6]))
    print(f"\n  wrote {RES/'slot_grammar.json'}, figures/slot_entropy.png, figures/affix_coverage.png")


if __name__ == "__main__":
    main()
